apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: test-app
      runAfter:
        - fetch-repo
      taskRef:
        name: run-unit-tests
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build-image
      runAfter:
        - test-app
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace